name: Open PR master-dev Into release

on:
  push:
    branches:
      - master-dev

jobs:
  main:
    name: Create PR master-dev to release
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          destination_branch: release
          pr_title: "[Automated] Merge ${{ github.ref_name }} into release"
          pr_body: "Automated Pull Request"
          pr_assignee: "adikurniawanid"
